apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "activemq.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: activemq
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: activemq
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: activemq
      name: {{ include "activemq.fullname" . }}  
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8161
              name: admin
            - containerPort: 61616
              name: broker
            - containerPort: 5672
              name: amqp
            - containerPort: 61613
              name: stomp
            - containerPort: 1883
              name: mqtt
            - containerPort: 61614
              name: websocket
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          #livenessProbe:
            #httpGet:
              #path: /
              #port: http
          #readinessProbe:
            #httpGet:
              #path: /
              #port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name:  {{ .Values.secret.registry }}
