apiVersion: v1
kind: Service
metadata:
  name: {{ include "activemq.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  sessionAffinity: {{ .Values.service.sessionAffinity }}
  ports:
{{ toYaml .Values.service.portList | indent 4 }}
  selector:
    app: activemq
